# ORACLE LINUX 7
build/test_oraclelinux_7_9.6:
	$(call test_rpm,oraclelinux,7,,9.6,9.6.24)
	touch build/test_oraclelinux_7_9.6

build/test_oraclelinux_7_10:
	$(call test_rpm,oraclelinux,7,,10,10.19)
	touch build/test_oraclelinux_7_10

build/test_oraclelinux_7_11:
	$(call test_rpm,oraclelinux,7,,11,11.14)
	touch build/test_oraclelinux_7_11

build/test_oraclelinux_7_12:
	$(call test_rpm,oraclelinux,7,,12,12.9)
	touch build/test_oraclelinux_7_12

build/test_oraclelinux_7_13:
	$(call test_rpm,oraclelinux,7,,13,13.5)
	touch build/test_oraclelinux_7_13

build/test_oraclelinux_7_14:
	$(call test_rpm,oraclelinux,7,,14,14.1)
	touch build/test_oraclelinux_7_14

# ORACLE LINUX 8
build/test_oraclelinux_8_9.6:
	$(call test_rpm,oraclelinux,8,,9.6,9.6.24)
	touch build/test_oraclelinux_8_9.6

build/test_oraclelinux_8_10:
	$(call test_rpm,oraclelinux,8,,10,10.19)
	touch build/test_oraclelinux_8_10

build/test_oraclelinux_8_11:
	$(call test_rpm,oraclelinux,8,,11,11.14)
	touch build/test_oraclelinux_8_11

build/test_oraclelinux_8_12:
	$(call test_rpm,oraclelinux,8,,12,12.9)
	touch build/test_oraclelinux_8_12

build/test_oraclelinux_8_13:
	$(call test_rpm,oraclelinux,8,,13,13.5)
	touch build/test_oraclelinux_8_13

build/test_oraclelinux_8_14:
	$(call test_rpm,oraclelinux,8,,14,14.1)
	touch build/test_oraclelinux_8_14
