# RHEL 7
build/test_rhel_7_9.6:
	$(call test_rpm,rhel,7,7Server,9.6,9.6.24)
	touch build/test_rhel_7_9.6

build/test_rhel_7_10:
	$(call test_rpm,rhel,7,7Server,10,10.19)
	touch build/test_rhel_7_10

build/test_rhel_7_11:
	$(call test_rpm,rhel,7,7Server,11,11.14)
	touch build/test_rhel_7_11

build/test_rhel_7_12:
	$(call test_rpm,rhel,7,7Server,12,12.9)
	touch build/test_rhel_7_12

build/test_rhel_7_13:
	$(call test_rpm,rhel,7,7Server,13,13.5)
	touch build/test_rhel_7_13

build/test_rhel_7_14:
	$(call test_rpm,rhel,7,7Server,14,14.1)
	touch build/test_rhel_7_14

# RHEL 8
build/test_rhel_8_9.6:
	$(call test_rpm,rhel,8,8Server,9.6,9.6.24)
	touch build/test_rhel_8_9.6

build/test_rhel_8_10:
	$(call test_rpm,rhel,8,8Server,10,10.19)
	touch build/test_rhel_8_10

build/test_rhel_8_11:
	$(call test_rpm,rhel,8,8Server,11,11.14)
	touch build/test_rhel_8_11

build/test_rhel_8_12:
	$(call test_rpm,rhel,8,8Server,12,12.9)
	touch build/test_rhel_8_12

build/test_rhel_8_13:
	$(call test_rpm,rhel,8,8Server,13,13.5)
	touch build/test_rhel_8_13

build/test_rhel_8_14:
	$(call test_rpm,rhel,8,8Server,14,14.1)
	touch build/test_rhel_8_14
