# RHEL 6
build/test_rhel_6_9.6:
	$(call test_rpm,rhel,6,6Server,9.6,9.6.21)
	touch build/test_rhel_6_9.6

build/test_rhel_6_10:
	$(call test_rpm,rhel,6,6Server,10,10.16)
	touch build/test_rhel_6_10

build/test_rhel_6_11:
	$(call test_rpm,rhel,6,6Server,11,11.11)
	touch build/test_rhel_6_11

build/test_rhel_6_12:
	$(call test_rpm,rhel,6,6Server,12,12.6)
	touch build/test_rhel_6_12

build/test_rhel_6_13:
	$(call test_rpm,rhel,6,6Server,13,13.2)
	touch build/test_rhel_6_13

# RHEL 7
build/test_rhel_7_9.6:
	$(call test_rpm,rhel,7,7Server,9.6,9.6.21)
	touch build/test_rhel_7_9.6

build/test_rhel_7_10:
	$(call test_rpm,rhel,7,7Server,10,10.16)
	touch build/test_rhel_7_10

build/test_rhel_7_11:
	$(call test_rpm,rhel,7,7Server,11,11.11)
	touch build/test_rhel_7_11

build/test_rhel_7_12:
	$(call test_rpm,rhel,7,7Server,12,12.6)
	touch build/test_rhel_7_12

build/test_rhel_7_13:
	$(call test_rpm,rhel,7,7Server,13,13.2)
	touch build/test_rhel_7_13

# RHEL 8
build/test_rhel_8_9.6:
	$(call test_rpm,rhel,8,8Server,9.6,9.6.21)
	touch build/test_rhel_8_9.6

build/test_rhel_8_10:
	$(call test_rpm,rhel,8,8Server,10,10.16)
	touch build/test_rhel_8_10

build/test_rhel_8_11:
	$(call test_rpm,rhel,8,8Server,11,11.11)
	touch build/test_rhel_8_11

build/test_rhel_8_12:
	$(call test_rpm,rhel,8,8Server,12,12.6)
	touch build/test_rhel_8_12

build/test_rhel_8_13:
	$(call test_rpm,rhel,8,8Server,13,13.2)
	touch build/test_rhel_8_13
