# CENTOS 7
build/test_centos_7_9.6:
	$(call test_rpm,centos,7,,9.6,9.6.24)
	touch build/test_centos_7_9.6

build/test_centos_7_10:
	$(call test_rpm,centos,7,,10,10.19)
	touch build/test_centos_7_10

build/test_centos_7_11:
	$(call test_rpm,centos,7,,11,11.14)
	touch build/test_centos_7_11

build/test_centos_7_12:
	$(call test_rpm,centos,7,,12,12.9)
	touch build/test_centos_7_12

build/test_centos_7_13:
	$(call test_rpm,centos,7,,13,13.5)
	touch build/test_centos_7_13

build/test_centos_7_14:
	$(call test_rpm,centos,7,,14,14.1)
	touch build/test_centos_7_14

# CENTOS 8
build/test_centos_8_9.6:
	$(call test_rpm,centos,8,,9.6,9.6.24)
	touch build/test_centos_8_9.6

build/test_centos_8_10:
	$(call test_rpm,centos,8,,10,10.19)
	touch build/test_centos_8_10

build/test_centos_8_11:
	$(call test_rpm,centos,8,,11,11.14)
	touch build/test_centos_8_11

build/test_centos_8_12:
	$(call test_rpm,centos,8,,12,12.9)
	touch build/test_centos_8_12

build/test_centos_8_13:
	$(call test_rpm,centos,8,,13,13.5)
	touch build/test_centos_8_13

build/test_centos_8_14:
	$(call test_rpm,centos,8,,14,14.1)
	touch build/test_centos_8_14
