# UBUNTU 16.04
build/test_ubuntu_16.04_9.6:
	$(call test_deb,ubuntu,16.04,xenial,9.6,9.6.21)
	touch build/test_ubuntu_16.04_9.6

build/test_ubuntu_16.04_10:
	$(call test_deb,ubuntu,16.04,xenial,10,10.16)
	touch build/test_ubuntu_16.04_10

build/test_ubuntu_16.04_11:
	$(call test_deb,ubuntu,16.04,xenial,11,11.11)
	touch build/test_ubuntu_16.04_11

build/test_ubuntu_16.04_12:
	$(call test_deb,ubuntu,16.04,xenial,12,12.6)
	touch build/test_ubuntu_16.04_12

build/test_ubuntu_16.04_13:
	$(call test_deb,ubuntu,16.04,xenial,13,13.2)
	touch build/test_ubuntu_16.04_13

# UBUNTU 18.04
build/test_ubuntu_18.04_9.6:
	$(call test_deb,ubuntu,18.04,bionic,9.6,9.6.21)
	touch build/test_ubuntu_18.04_9.6

build/test_ubuntu_18.04_10:
	$(call test_deb,ubuntu,18.04,bionic,10,10.16)
	touch build/test_ubuntu_18.04_10

build/test_ubuntu_18.04_11:
	$(call test_deb,ubuntu,18.04,bionic,11,11.11)
	touch build/test_ubuntu_18.04_11

build/test_ubuntu_18.04_12:
	$(call test_deb,ubuntu,18.04,bionic,12,12.6)
	touch build/test_ubuntu_18.04_12

build/test_ubuntu_18.04_13:
	$(call test_deb,ubuntu,18.04,bionic,13,13.2)
	touch build/test_ubuntu_18.04_13

# UBUNTU 20.04
build/test_ubuntu_20.04_9.6:
	$(call test_deb,ubuntu,20.04,focal,9.6,9.6.21)
	touch build/test_ubuntu_20.04_9.6

build/test_ubuntu_20.04_10:
	$(call test_deb,ubuntu,20.04,focal,10,10.16)
	touch build/test_ubuntu_20.04_10

build/test_ubuntu_20.04_11:
	$(call test_deb,ubuntu,20.04,focal,11,11.11)
	touch build/test_ubuntu_20.04_11

build/test_ubuntu_20.04_12:
	$(call test_deb,ubuntu,20.04,focal,12,12.6)
	touch build/test_ubuntu_20.04_12

build/test_ubuntu_20.04_13:
	$(call test_deb,ubuntu,20.04,focal,13,13.2)
	touch build/test_ubuntu_20.04_13
