# Suse 15.1
build/test_suse_15.1_9.5:
	$(call test_suse,suse,15.1,,9.5,9.5.25)
	touch build/test_suse_15.1_9.5

build/test_suse_15.1_9.6:
	$(call test_suse,suse,15.1,,9.6,9.6.21)
	touch build/test_suse_15.1_9.6

build/test_suse_15.1_10:
	$(call test_suse,suse,15.1,,10,10.16)
	touch build/test_suse_15.1_10

build/test_suse_15.1_11:
	$(call test_suse,suse,15.1,,11,11.11)
	touch build/test_suse_15.1_11

build/test_suse_15.1_12:
	$(call test_suse,suse,15.1,,12,12.6)
	touch build/test_suse_15.1_12

build/test_suse_15.1_13:
	$(call test_suse,suse,15.1,,13,13.2)
	touch build/test_suse_15.1_13

# Suse 15.2
build/test_suse_15.2_9.5:
	$(call test_suse,suse,15.2,,9.5,9.5.25)
	touch build/test_suse_15.2_9.5

build/test_suse_15.2_9.6:
	$(call test_suse,suse,15.2,,9.6,9.6.21)
	touch build/test_suse_15.2_9.6

build/test_suse_15.2_10:
	$(call test_suse,suse,15.2,,10,10.16)
	touch build/test_suse_15.2_10

build/test_suse_15.2_11:
	$(call test_suse,suse,15.2,,11,11.11)
	touch build/test_suse_15.2_11

build/test_suse_15.2_12:
	$(call test_suse,suse,15.2,,12,12.6)
	touch build/test_suse_15.2_12

build/test_suse_15.2_13:
	$(call test_suse,suse,15.2,,13,13.2)
	touch build/test_suse_15.2_13
