FROM ololobus/postgres-dev:stretch

USER root
RUN apt-get update
RUN apt-get -yq install python3 python3-pip

# RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
# RUN python2 get-pip.py
RUN python3 -m pip install virtualenv

# Environment
ENV PG_MAJOR=${PG_VERSION} PG_BRANCH=${PG_BRANCH}
ENV LANG=C.UTF-8 PGHOME=/pg/testdir/pgbin

# Make directories
RUN	mkdir -p /pg/testdir

COPY run_tests.sh /run.sh
RUN chmod 755 /run.sh

COPY . /pg/testdir
WORKDIR /pg/testdir

# Grant privileges
RUN	chown -R postgres:postgres /pg/testdir

USER postgres
ENTRYPOINT MODE=${MODE} /run.sh
