# ALT 7
build/alt_7_9.5:
	$(call build_alt,alt,7,,9.5,9.5.25)
	touch build/alt_7_9.5

build/alt_7_9.6:
	$(call build_alt,alt,7,,9.6,9.6.21)
	touch build/alt_7_9.6

build/alt_7_10:
	$(call build_alt,alt,7,,10,10.17)
	touch build/alt_7_10

build/alt_7_11:
	$(call build_alt,alt,7,,11,11.11)
	touch build/alt_7_11

build/alt_7_12:
	$(call build_alt,alt,7,,12,12.6)
	touch build/alt_7_12

build/alt_7_13:
	$(call build_alt,alt,7,,13,13.2)
	touch build/alt_7_13
